leaveprogram=0
while leaveprogram != "e":
    import random
    print("This is the magic 8 box.")
    print("Ask it a question and hit ENTER")
    input()
    number=random.randint(1, 6)
    if number==1:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \  It is certain   /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==2:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \It is decidedly so/              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==3:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \     Without a      /             ]")
        print("{              \      doubt       /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==4:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \ Yes, definitely  /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==5:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \You may rely on it/              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==6:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \ As I see it, yes /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==7:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \    Most likely   /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==8:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \   Outlook good   /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==9:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \       Yes        /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==10:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \ Signs point to yes /             ]")
        print("{              \                  /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==11:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \     Reply hazy     /             ]")
        print("{              \    try again     /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==12:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \  Ask again later /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==13:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \ Better not tell  /              ]")
        print("{               \  tell you now  /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==14:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \Cannot predict now/              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==15:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \    Concentrate   /              ]")
        print("{               \    and ask     /               ]")
        print("{                \    again     /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==16:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \    Don't count   /              ]")
        print("{               \     on it      /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==17:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \     My reply     /              ]")
        print("{               \     is no      /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==18:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \   My sources     /              ]")
        print("{               \    say no      /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==19:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \    Outlook not   /              ]")
        print("{               \    so good     /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
    if number==20:
        print("{------------------------------------------------]")
        print("{                                                ]")
        print("{          ----------------------------          ]")
        print("{          \                          /          ]")
        print("{           \                        /           ]")
        print("{            \                      /            ]")
        print("{             \                    /             ]")
        print("{              \  Very doubtful   /              ]")
        print("{               \                /               ]")
        print("{                \              /                ]")
        print("{                 \            /                 ]")
        print("{                  \          /                  ]")
        print("{                   \        /                   ]")
        print("{                    \      /                    ]")
        print("{                     \    /                     ]")
        print("{                      \  /                      ]")
        print("{                       \/                       ]")
        print("{------------------------------------------------]")
        print()
        print("Hit 'E' to end game.")
        leaveprogram=input()
